# This action renders PlantUML diagrams and pushes the
# resulting PNG file to your wiki repo.
#
# As it does not use the public PlantUML render service
# but an intance of the PlantUML Java app, this action
# doesnt leak your documentation to the public and can
# therefore be used in private repositories.

name: Render Latest PlantUML to Wiki Extended
description: Action forked from frederikheld to allow more customization, published png to wiki from plantuml
branding:
    icon: file-text
    color: blue

inputs:
    WIKI_TOKEN:
        description: Secure token to access wiki repo
        required: true
    INPUT_DIR:
        description: Directory in repo to read PlantUML source files from
        default: /input_directory
    OUTPUT_DIR:
        description: Directory in wiki to write rendered diagrams to
        default: /output_directory

runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.WIKI_TOKEN }}
        - ${{ inputs.INPUT_DIR }}
        - ${{ inputs.OUTPUT_DIR }}
        - ${{ inputs.JAVA_ARGS }}
